import numpy as np
import sys
from pathlib import Path
import argparse as ag


cc = 299792458.0 #Speed of light

# NumPy 2.0 removed np.trapz in favour of np.trapezoid. Alias rather than
# calling np.trapz directly so this works on both.
_trapz = np.trapezoid if hasattr(np, "trapezoid") else np.trapz

# ExoPlaSim resamples onto the model's wavelength grid with np.interp, which is
# a POINT SAMPLE. A point sample of a line-blanketed photospheric spectrum lands
# in the continuum more often than in a line core, so it reads high; line
# density is highest in the blue, so it reads highest there. The shortwave
# scheme divides its two bands at 0.75 um and weights every two-band surface
# albedo by the share below the split, so the bias lands directly on the
# surface energy balance. an independent BT-Settl grid measures it
# against an independently produced copy of the same BT-Settl grid.
#
# The replacement integrates the source across each output bin and divides by
# the bin width, so the output's own trapezoidal integral reproduces the
# source's. Bin edges are the ARITHMETIC midpoints of the output grid, because
# that is the choice under which np.trapz over the output equals the sum of the
# bin integrals exactly: the trapezoidal weight of an interior sample is
# already (w[i+1] - w[i-1])/2, which is the width of its midpoint bin.

def _cumulative_flux(wvls,fluxes):
    """Running trapezoidal integral of ``fluxes`` over ``wvls``, starting at 0."""
    return np.concatenate(([0.0],np.cumsum(0.5*(fluxes[1:]+fluxes[:-1])
                                           *np.diff(wvls))))

def _integral_below(x,wvls,fluxes,cumulative):
    """Exact piecewise-linear integral from wvls[0] up to each x.

    Interpolating ``cumulative`` directly would be linear across a source
    interval over which the true integral is quadratic; this closes the partial
    interval with its own trapezoid instead. Outside the source support the
    integral is clamped, so an output bin beyond the data contributes nothing
    rather than extrapolating.
    """
    x = np.clip(x,wvls[0],wvls[-1])
    i = np.clip(np.searchsorted(wvls,x,side="right")-1,0,wvls.size-2)
    fx = fluxes[i]+(fluxes[i+1]-fluxes[i])*(x-wvls[i])/(wvls[i+1]-wvls[i])
    return cumulative[i]+0.5*(fluxes[i]+fx)*(x-wvls[i])

def _rebin_conserving(wnew,wvls,fluxes):
    """Resample onto ``wnew`` conserving flux, in place of np.interp.

    Returns the mean flux density in each output bin, the bins tiling ``wnew``
    at its arithmetic midpoints.
    """
    edges = np.empty(wnew.size+1)
    edges[1:-1] = 0.5*(wnew[:-1]+wnew[1:])
    edges[0] = wnew[0]-0.5*(wnew[1]-wnew[0])
    edges[-1] = wnew[-1]+0.5*(wnew[-1]-wnew[-2])
    cumulative = _cumulative_flux(wvls,fluxes)
    return np.diff(_integral_below(edges,wvls,fluxes,cumulative))/np.diff(edges)

def readspec(sfile,cgs=False):
    """Read a Phoenix stellar spectrum and return wavelengths, fluxes, and units
    
    Takes as input a spectrum file generated by the Phoenix stellar spectrum web simulator,
    https://phoenix.ens-lyon.fr/simulator-jsf22-26.
    
    Parameters
    ----------
    sfile : str
        Path to the spectrum file
    cgs : bool, optional
        Whether or not we should try to use CGS units (irrelevant for exoplasim)
        
    Returns
    -------
    numpy.ndarray, numpy.ndarray, str
        Returns wavelengths, fluxes, and the units
    """
    f=open(sfile,"r")
    ftxt = f.read()
    if ftxt[0]=='#':
       newstyle=True
    else:
       newstyle=False
    f.close()
    if newstyle:
       lines = ftxt.split('\n')[:-2] #chop off timing line
       nhl = 0
       for entry in lines:
          if entry[0]=='#':
             nhl+=1
          else:
             break
       units = lines[nhl-2].split()[-1]
       if lines[nhl-2].split()[1]=="(ANGSTROM)":
          cgs=False
       nhi = 0
       for entry in lines[nhl:]:
          if float(entry.split()[0])<0.1: #angstroms
             nhi+=1
          else:
             break
       print("Cutting at %d: "%(nhl+nhi),lines[nhl+nhi])
       lines = lines[nhl+nhi:]
       wvls = np.zeros(len(lines))
       fluxes = np.zeros(len(lines))
       n=0
       for l in lines:
          wvls[n] = float(l.split()[0])
          fluxes[n] = float(l.split()[1])
          n+=1
          #print l.split()
    else:      
       lines = ftxt.split('\n')[:-1]
       wvls = np.zeros(len(lines))
       fluxes = np.zeros(len(lines))
       n=0
       for l in lines:
           wvls[n] = float(l.split()[0])
           fluxes[n] = 10**(float(l.split()[1].replace('D','E'))-8.0)
           n+=1
       units='ergs/sec/cm^2/angstrom'
    if not cgs:
        units='W/m^2/micron'
        wvls[:] = wvls[:]*1.0e-4 #microns
        fluxes[:] = fluxes[:]*10.0 #W/m^2/micron
    return wvls,fluxes,units

def _coarsen(wvls,fluxes,w1,w2,num=5000):
    inds = np.arange(len(wvls))
    nlow = (inds[wvls>w1])[0]
    nhigh= (inds[wvls>w2])[0]
    
    inc = int(nhigh-nlow)//num
    
    waves = np.zeros(num)
    energ = wvls*fluxes
    flxs2 = np.zeros(num)
    
    for n in range(0,num):
        v0 = nlow+n*inc-1
        v1 = nlow+n*inc
        intg = 0.0
        for v in range(0,inc):
            intg+=0.5*(wvls[v1+v]-wvls[v0+v])*(fluxes[v1+v]+fluxes[v0+v])
        dnu = wvls[v1+inc]-wvls[v0]
        waves[n] = 0.5*(wvls[v1+inc]+wvls[v0])
        flxs2[n] = intg/dnu
        
    return waves,flxs2

def _integrate_trap(x,y):
    net = 0
    for n in range(1,len(y)):
        net += 0.5*(x[n]-x[n-1])*(y[n]+y[n-1])
    return net

def _normalize(wvls,fluxes):
    netf = _trapz(fluxes,x=wvls)
    factor = 1366.941858/netf
    return fluxes*factor

def writedat(wvls,fluxes,name):
    """Write wavelengths and fluxes to a .dat file ExoPlaSim can read.
    
    Parameters
    ----------
    wvls : array-like
        An array-like object containing a monotonic list of wavelengths going from short to long
    fluxes : array-like
        An array-like object containing a flux for each wavelength in ``wvls``.
    name : str
        A name to use when generating output files.
        
    Yields
    ------
    name.dat
        The provided spectrum in a format ExoPlaSim can read.
    """
    f=open(name+".dat","w")
    sdat = ' Wavelength    Flux  \n'
    for n in range(0,len(wvls)):
        sdat+=str(wvls[n])+' '+str(fluxes[n])+'\n'
    f.write(sdat)
    f.close()
    
def _processArgs():
    
    parser = ag.ArgumentParser(description="""Convert spectral files to exoplasim-compliant formats, including resampling to the necessary resolutions.
                               
    Must give as input a spectrum file generated by the Phoenix stellar spectrum web simulator,
    https://phoenix.ens-lyon.fr/simulator-jsf22-26.""")
    parser.add_argument("spectrumfile",help="Path to the spectrum file",)
    parser.add_argument("name",help="Name of the star")
    parser.add_argument("-p","--plot",action="store_true",help="Display plots of the converted spectrum")
    parser.add_argument('-w',"--numwavelengths",default=2048,type=int,help="Number of wavelengths in the hi-res spectrum")
    parser.add_argument('-n',"--normalize",action="store_true",help="Normalize the output spectra")
    args = parser.parse_args()
    
    return args
    
def convert(spectrumfile, name, plot=False, numwavelengths=2048, normalize=False):
    """Convert spectral files to exoplasim-compliant formats, including resampling to the necessary resolutions.

    Must give as input a spectrum file generated by the Phoenix stellar spectrum web simulator,
    https://phoenix.ens-lyon.fr/simulator-jsf22-26. 
    
    Parameters
    ----------------
    spectrumfile : str
        Path to the file to convert
    name : str  
        Identifying name for the star to use in filenames
    plot : bool, optional
        If set, will plot the spectra. Requires matplotlib
    numwavelengths : int, optional
        Number of wavelengths to use for the hi-res spectrum. Default 2048
    normalize : bool, optional
        If set, output spectra will be normalized.

    Yields
    ------
    mystarsname.dat
        965 wavelengths
    mystarsname_hr.dat
        2048 wavelengths
        
    """
    
    sfile = spectrumfile
    #wave0 = float(sys.argv[3]) #microns
    #wave1 = float(sys.argv[4]) #microns
    numw = numwavelengths
    norm = normalize
    w,f,u = readspec(sfile)
    print(u,w.min(),w.max())
    if plot:
        import matplotlib.pyplot as plt
        plt.plot(w,f)
        plt.xscale('log')
        plt.yscale('log')
        plt.show()
    #wc,fc = _coarsen(w,f,wave0,wave1,num=numw*4)
    #plt.plot(wc,fc)
    #plt.xscale('log')
    #plt.yscale('log')
    #plt.xlabel("$\lambda$ [$\mu$m]")
    #plt.ylabel("$F_\lambda$ [W/m$^2$/$\mu$m]")
    #plt.show()
    w2 = np.concatenate([np.geomspace(0.2,0.75,num=int(numw/2)+1)[:-1],np.geomspace(0.75,100.0,num=int(numw/2))])
    if plot:
        plt.plot(w2)
        plt.yscale('log')
        plt.show()
    f2 = _rebin_conserving(w2,w,f)
    E0 = _trapz(f,x=w)
    E1 = _trapz(f2,x=w2)
    print(abs(E0-E1)/E0)
    factor = 1.0
    if norm:
        factor = 1366.941858/E1
        f2*=factor
        print(_trapz(f2,x=w2))
        print(_trapz(_normalize(w,f),x=w))
    #print f2[np.argwhere(w2>40.0)],w[-10:]
    if plot:
        plt.plot(w2,f2)
        #plt.plot(wc,fc)
        plt.xscale('log')
        plt.yscale('log')
        plt.xlabel("$\lambda$ [$\mu$m]")
        plt.ylabel("$F_\lambda$ [W/m$^2$/$\mu$m]")
        plt.show()
    wvref = np.loadtxt(Path(__file__).parent.resolve()/"wvref.txt")
    # Rebinned from the SOURCE rather than from f2. wvref carries only 41
    # points between 0.34 and 0.75 um, so resampling the already-resampled
    # array would reintroduce the sampling bias exactly where it is worst, and
    # it would throw away resolution beyond 2 um where wvref is the finer grid
    # of the two. `factor` keeps normalize= meaning what it did.
    f3 = _rebin_conserving(wvref,w,f)*factor
    writedat(w2,f2/cc,name+"_hr")
    writedat(wvref,f3/cc,name)
    if plot:
        plt.plot(wvref,f3)
        plt.xscale('log')
        plt.yscale('log')
        plt.xlabel("$\lambda$ [$\mu$m]")
        plt.ylabel("$\lambda F_\lambda$ [W/m$^2$]")
        plt.show()
    
def main():
    """Convert spectral files to exoplasim-compliant formats, including resampling to the necessary resolutions.

    Must give as input a spectrum file generated by the Phoenix stellar spectrum web simulator,
    https://phoenix.ens-lyon.fr/simulator-jsf22-26. **Do not use as an imported function; only call directly as a command-line program.**

    **Usage**
    
    >>> python makestellarspec.py [spectrumfile] [name] --plot --numwavelengths --normalize
    
    Parameters
    ----------------
    -p, --plot : bool, optional
        If set, will plot the spectra. Requires matplotlib
    -w, --numwavelengths : int, optional
        Number of wavelengths to use for the hi-res spectrum. Default 2048
    -n, --normalize : bool, optional
        If set, output spectra will be normalized.

    Yields
    ------
    mystarsname.dat
        965 wavelengths
    mystarsname_hr.dat
        2048 wavelengths

    """
    args = _processArgs()
    if args.plot:
        import matplotlib.pyplot as plt
    
    sfile = args.spectrumfile
    name = args.name
    #wave0 = float(sys.argv[3]) #microns
    #wave1 = float(sys.argv[4]) #microns
    numw = args.numwavelengths
    norm = args.normalize
    w,f,u = readspec(sfile)
    print(u,w.min(),w.max())
    if args.plot:
        plt.plot(w,f)
        plt.xscale('log')
        plt.yscale('log')
        plt.show()
    #wc,fc = _coarsen(w,f,wave0,wave1,num=numw*4)
    #plt.plot(wc,fc)
    #plt.xscale('log')
    #plt.yscale('log')
    #plt.xlabel("$\lambda$ [$\mu$m]")
    #plt.ylabel("$F_\lambda$ [W/m$^2$/$\mu$m]")
    #plt.show()
    w2 = np.concatenate([np.geomspace(0.2,0.75,num=int(numw/2)+1)[:-1],np.geomspace(0.75,100.0,num=int(numw/2))])
    if args.plot:
        plt.plot(w2)
        plt.yscale('log')
        plt.show()
    f2 = _rebin_conserving(w2,w,f)
    E0 = _trapz(f,x=w)
    E1 = _trapz(f2,x=w2)
    print(abs(E0-E1)/E0)
    factor = 1.0
    if norm:
        factor = 1366.941858/E1
        f2*=factor
        print(_trapz(f2,x=w2))
        print(_trapz(_normalize(w,f),x=w))
    #print f2[np.argwhere(w2>40.0)],w[-10:]
    if args.plot:
        plt.plot(w2,f2)
        #plt.plot(wc,fc)
        plt.xscale('log')
        plt.yscale('log')
        plt.xlabel("$\lambda$ [$\mu$m]")
        plt.ylabel("$F_\lambda$ [W/m$^2$/$\mu$m]")
        plt.show()
    wvref = np.loadtxt(Path(__file__).parent.resolve()/"wvref.txt")
    # Rebinned from the SOURCE rather than from f2. wvref carries only 41
    # points between 0.34 and 0.75 um, so resampling the already-resampled
    # array would reintroduce the sampling bias exactly where it is worst, and
    # it would throw away resolution beyond 2 um where wvref is the finer grid
    # of the two. `factor` keeps normalize= meaning what it did.
    f3 = _rebin_conserving(wvref,w,f)*factor
    writedat(w2,f2/cc,name+"_hr")
    writedat(wvref,f3/cc,name)
    if args.plot:
        plt.plot(wvref,f3)
        plt.xscale('log')
        plt.yscale('log')
        plt.xlabel("$\lambda$ [$\mu$m]")
        plt.ylabel("$\lambda F_\lambda$ [W/m$^2$]")
        plt.show()

if __name__=="__main__" and (Path(sys.argv[0]).name!="sphinx-build" and 
                             Path(sys.argv[0]).name!="build.py"):
    main()
